### PR TITLE
feat: add admin setting to restrict rooms

### LINKED ISSUE #43: Admin settings to limit user options
**Is your feature request related to a problem? Please describe.**
On our Nextcloud instance we would like to limit what options our users have. For example we might not want all users to be able to use recordings, have unlimited rooms or to have unlimited participants in their rooms.

**Describe the solution you'd like**
As part of an admin settings page (or the existing admin settings on the additional settings page) it would be great to have these options:
1. Disable recordings for rooms.
2. Set max number of rooms for each user.
3. Set maximum limit for "max participant in room" for all rooms.

Additionally it would be even better to be able to decide what groups to apply these restrictions to, or to select groups not to apply the restrictions to. Not sure what the best solution would be for this but it would allow more flexibility. 

E.g most nextcloud users can only create a single room with no recording and max 4 participants, users in moderator group could create max 5 rooms with 100 participants and recordings, and users in admin group could create unlimited rooms with unlimited participants and recording.

Limiting by group would be useful for reducing pressure on BBB server and for those who have different user tiers on their nextcloud server.

**Describe alternatives you've considered**
I was looking at doing this just for our own server by hiding the columns entirely, but realized it would be better to have the option to do this from the admin settings.

**Additional context**
These are all functions that would be useful for our own usage. I would personally say that being able to disable recordings for users is the most useful, followed by being able to limit their number of participants and rooms. Limiting only to groups would also be very useful but I can imagine that being a much harder feature to implement.

### LINKED ISSUE #53: No meeting access for users not in restricted groups
**Describe the bug**
In my Nextcloud, BigBlueButton Integration is restricted to members of a special group (called "bbb"). Only group members are allowed to create or modify meetings ("rooms"). That's Ok. 
The Bug: A user, not member of "bbb"-group and logged in to nextcloud, can not participate in any meeting. If he loggs out of nextcloud, meeting participation works.

**To Reproduce**
1. add a group "bbb": nextcloud/settings/user; let a user ("bbbuser") become a member of this group
2. restrict acces to BigBlueButton: nextcloud/settings/apps/installed/bbb; right panel "restrict to groups" bbb (see screenshot)
3. log in to nextcloud as the "bbbuser", create a bbb-meeting (nextcloud/user/bbb), copy meeting-url
4. log out from nextcloud, go to the meeting by pasting the copied url: you are requested for your name - do nothing
5. log in to nextcloud as a user not member of group "bbb"
6. in a second browser tab or browser window, paste the meeting url - you are now not in the meeting, you are at your nextcloud startpage!

**Expected behavior**
Every user should have access to a meeting, independently from the login state to nextcloud!

**Screenshots**
image

**System (please complete the following information):**
 - Browser with version firefox 68.7.0esr, chromium  81.0.4044.92 
 - App version 0.5.1
 - Nextcloud version 18.0.6
 - BigBlueButton version: bbb-conf --version: bigbluebutton 1:2.2.0-5
 - Is your BigBlueButton instance working with Greenligh? no
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

no error rel

**Javascript log:**

### PR DESCRIPTION
**Pull request by sualko**
This pull requests allows administrators to limit the amount of settings each user can configure. The following restrictions are possible on a group/global level:

- maximum number of rooms. If the global limit is set to 0 no one can create a room, but rooms can still be shared with everyone. For this reason the room manager is also visible to everyone. If multiple rules apply for a user, the maximum is chosen.
- access types. All matching rules are combined.
- max participants limit. The maximum of all valid restrictions is applied. For example if the global default is 0, you can define an unlimited rule for another group. This is also true for the max. room property.
- recordings. Once the user is in a group which allows recordings, he can enable the recording feature.

@digitalrevisor @jacotec @remmedia @garblixa would be great if you could test this, before I merge it into master.

2020-08-28 11 58 08 localhost 281490b69039

fix #43
fix #53

### CODE REVIEW

**Comment by garblixa** [comment]
Hello Klaus,

many thanks for this enhancement!
Unfortunately I do not have a development environment to build and test the package. But I'm happy to report possible errors if you have integrated the changes.

Kind regards
Klaus

**Comment by sualko** [comment]
@garblixa no problem. Thanks for your reply.

I changed the behavior of the room restriction, it works now similar to all other options. Means access options are combined from all matching rules. I changed the description above accordingly.

**Comment by digitalrevisor** [comment]
Hello @sualko . This is very cool. I've installed it on our development enviroment to make some tests. It seems to be working fine so far. Only problem I've had is trying to turn off recordings for a group. I get a 500 server error when I do that. Maybe problem when with my installation but I don't know. I attached an image showing the error.

error1

I think these features will be very useful for many. I atleast know it is helpful for our use cases.

**Comment by sualko** [comment]
@digitalrevisor thanks for testing. Can you provide the response from this request and maybe the corresponding nc log entry? Because I'm unable to reproduce your behaviour.

**Comment by sualko** [comment]
I did some more tests and it seams to be stable. Therefore I merge it now. If you find any bugs with this feature, please open a new issue.

**Pull request merged**
